### ISSUE TITLE
Is there a 3.8 python runtime available?

### ISSUE THREAD

**Issue by dokutoshi** [iandow/mediainfo_aws_lambda#1]
Building a lambda layer 3.8 generates an import error for a 3.8 lambda runtime. @ianwow

**Comment by ianwow** [comment]
If you're not already, try using the layered approach:

https://github.com/iandow/mediainfo_aws_lambda#deploy-option-2-preferred---lambda-function-with-libraries-as-lambda-layers

I'm also getting an import error with the allinone approach, but the layered approach seems to work.
