### ISSUE TITLE
Python 3.9 /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by wittyapps** [iandow/mediainfo_aws_lambda#11]
After building python 3.9 pymediainfo library I get this error message when trying to invoke the app.py Lambda function.

{"errorMessage": "Failed to load library from libmediainfo.so.0 - /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/python/libmediainfo.so.0)", "errorType": "OSError", "stackTrace": ["  File \"/var/task/app.py\", line 72, in lambda_handler\n    media_info = MediaInfo.parse(tmp_filename)\n", "  File \"/opt/python/lib/python3.8/site-packages/pymediainfo/__init__.py\", line 431, in parse\n    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)\n", "  File \"/opt/python/lib/python3.8/site-packages/pymediainfo/__init__.py\", line 329, in _get_library\n    raise OSError(\n"]}{
    "FunctionError": "Unhandled", 
    "ExecutedVersion": "$LATEST", 
    "StatusCode": 200
}

**Comment by JonathanMorley2** [comment]
Hi @wittyapps did you find the issue with GLIBC_2.27 missing. I've run into the same issue just now.

**Comment by hbouachir** [comment]
Hi Guys,
for me I change the image :
**FROM amazonlinux:2022**
then I worked with Python 3.12.0,
you can find below Dockerfile updated:

``
# PURPOSE: This Dockerfile will prepare an Amazon Linux docker image with everything needed to compile binary MediaInfo libraries for Python 3.7 and Python 3.8
# USAGE: 
# 1. Build the docker image:
#     docker build --tag=pymediainfo-layer-factory:latest .
# 2. Build and copy MediaInfo libraries to ./pymediainfo-python[37,38].zip
#     docker run --rm -it -v $(pwd):/data pymediainfo-layer-factory cp /packages/pymediainfo-python37.zip /data

FROM amazonlinux:2022

WORKDIR /
#RUN yum update -y
RUN yum install gcc gcc-c++ openssl-devel bzip2-devel libffi-devel wget tar gzip zip make zlib-devel -y

# Install Python 3.9
WORKDIR /
RUN wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
RUN tar -xzf Python-3.12.0.tgz
WORKDIR /Python-3.12.0
RUN ./configure --enable-optimizations
RUN make install



# Install Python packages
RUN mkdir /packages
RUN echo "pymediainfo" >> /packages/requirements.txt

RUN mkdir -p /packages/pymediainfo-3.12/python/lib/python3.12/site-packages
# Install importlib-metadata for Python 3.7
RUN pip3.12 install importlib-metadata
#RUN pip install typing-extensions


RUN pip3.12 install -r /packages/requirements.txt -t /packages/pymediainfo-3.12/python/lib/python3.12/site-packages



# Download MediaInfo
WORKDIR /root
RUN wget https://mediaarea.net/download/binary/libmediainfo0/19.09/MediaInfo_DLL_19.09_GNU_FromSource.tar.gz
RUN tar -xzvf MediaInfo_DLL_19.09_GNU_FromSource.tar.gz

# Compile MediaInfo with Support for URL Inputs
WORKDIR /root/MediaInfo_DLL_GNU_FromSource/
RUN ./SO_Compile.sh

# Create zip files for Lambda Layer deployment

RUN cp /root/MediaInfo_DLL_GNU_FromSource/MediaInfoLib/Project/GNU/Library/.libs/* /packages/pymediainfo-3.12/python
RUN cp /root/MediaInfo_DLL_GNU_FromSource/MediaInfoLib/Project/GNU/Library/.libs/* /packages/pymediainfo-3.12/
WORKDIR /packages/pymediainfo-3.12/
RUN zip -r9 /packages/pymediainfo-python312.zip .
WORKDIR /packages/
RUN rm -rf /packages/pymediainfo-3.12/
``

**Comment by iandow** [comment]
@hbouachir Thanks for your contribution. I merged your Dockerfile changes.
