### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by weiping-bj** [iandow/mediainfo_aws_lambda#3]
I flowed all process mentioned in an [AWS blog](https://aws.amazon.com/cn/blogs/media/running-mediainfo-as-an-aws-lambda-function/) and published the MediaInfo Python library as a Lambda layer. 

But I got an error when I tried to invoke lambda: 
```
[ERROR] OSError: libmediainfo.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/var/task/app.py", line 43, in lambda_handler
    media_info = MediaInfo.parse(signed_url)
  File "/opt/python/lib/python3.7/site-packages/pymediainfo/__init__.py", line 306, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/opt/python/lib/python3.7/site-packages/pymediainfo/__init__.py", line 197, in _get_library
    lib = lib_type(library)
  File "/var/lang/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
```
It seems that Lambda function did not import MediaInfo from layer correctly. 

My basic environment is as below:
Region: ap-northeast-1
AMI: ami-0c3ae97724b825432 (Amazon Linux)
Python in Lambda: 3.7

Could you guide me to fix this issue?

Thanks.

**Comment by iandow** [comment]
I just accepted https://github.com/iandow/mediainfo_aws_lambda/pull/2 to this repo so that the path to libmediainfo.so is explicitly specified. You might want to try following the instructions in this repo's README to see if it works with this new change.

**Comment by weiping-bj** [comment]
> I just accepted #2 to this repo so that the path to libmediainfo.so is explicitly specified. You might want to try following the instructions in this repo's README to see if it works with this new change.

It works. Thanks for your help.
