### ISSUE TITLE
Uprading to Python Version 3.9?

### ISSUE THREAD

**Issue by vincentdory** [iandow/mediainfo_aws_lambda#7]
Hello,

I've been using this project to add the Mediainfo dependency to an Python 3.7 AWS Lambda that I have been using. Recently, I have received the task of upgrading the lambda to Python 3.9, and I've tried to update the Dockerfile to pull files for Python 3.9 rather than 3.7 and 3.8, but the resulting zip file is smaller in size and is missing some site-packages (notably setuptools).

Is there any special consideration I need to take into account to upgrade to 3.9? Also, are there changes that add Python 3.9 support to this project?

Thanks!

**Comment by iandow** [comment]
@vincentdory I've added Python 3.9 support in https://github.com/iandow/mediainfo_aws_lambda/tree/add_python39. Does that branch work for you?

**Comment by vincentdory** [comment]
Yes, this branch works. Thanks!
